### PR TITLE
Feature/forms fix

### LINKED ISSUE #573: All form fields show up but you can't enter text
Im still having trouble creating properties. I have got as far as the form but im locked out of editing any of the fields:

http://www.getembed.com/app#511d6530-f227-4279-be56-93e95283e41a,158dc07f-6450-4615-ab41-233b92225eeb

### PR DESCRIPTION
**Pull request by annapawlicka**
- Upgrades cljs (giving us recompilation of dependant namespaces) and om to latest versions.
- Updates all input forms to use local state.
- Updates alert pop ups to use local state as well (to prevent popups from triggering render of forms).
- Fixes an issue where parsing errors from validating entities were causing exception: validation error returned is a clojure map, not a schema validation error
- Fixes an issue where `(last (str/split uri #"/"))` returned hostname only if the uri stored in db was invalid.
- Fixes a bug in raw data tab where sensor was joined using `"-"` instead of `"~"`.
- Fixes an issue in calculated sensors logic - when the user PUT all existing sensors (with only certain sensor being actually updated), all sensors were recreated, and old ones were not deleted.

Fixes #573

### CODE REVIEW

File: src/cljs/kixi/hecuba/tabs/hierarchy/datasets.cljs [hunk 1]
```diff
@@ -328,17 +326,18 @@
...
         (let [{:keys [dropdown-chan]} (om/get-state owner)
-              {:keys [path value]}    (<! dropdown-chan)]
-          (om/update! selected-dataset path (if (= path [:field])
-                                              (str value "~" (-> (filter #(= (:value %) value) available-fields)
-                                                                 first
-                                                                 :unit))
-                                              value)))
+              {:keys [path value]}    (<! dropdown-chan)
+              v (if (= path [:field])
+                  (str value "~" (-> (filter #(= (:value %) value) available-fields) first :unit))
```
Comment (otfrom) [inline src/cljs/kixi/hecuba/tabs/hierarchy/datasets.cljs]: not a problem in this instance now, but if we were to add a function after :unit I'd be thrown off by doing a seq thread first (->) rather than thread last (->>). So I'd prefer it to look like this:

```
(->> available-fields (filter #(= (:value %) value)) first :unit)
```

File: src/cljs/kixi/hecuba/tabs/hierarchy/devices.cljs [hunk 2]
```diff
@@ -167,13 +141,16 @@
...
+                       (error-handler owner)))
 
 (defn save-edited-device [event-chan existing-device refresh-chan owner property_id device_id]
   (let [{:keys [device sensors]} (om/get-state owner)
         device (-> device
-                   (cond-> (:privacy device) (update-in [:privacy] str)))
-        readings (into [] (map (fn [[k v]] (assoc v :sensor_id k)) sensors))]
+                   (dissoc :synthetic :editable :metering_point_id :metadata)
+                   (update-in [:privacy] str))
+        readings (into [] (map (fn [[k v]] (-> (assoc v :sensor_id k)
```
Comment (otfrom) [inline src/cljs/kixi/hecuba/tabs/hierarchy/devices.cljs]: mapv rather than (into []..)?

**Comment by otfrom** [comment]
Just nitpicking :shipit:

**Comment by otfrom** [comment]
:shipit:
